In [1]:
#MY CODE FOR NEURAL NETWORKS WITH NO HIDDEN LAYER:
#this is to implement OR  function

In [2]:
import numpy as np


In [64]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [65]:
#forward propagation
def sig(z):
    return 1/(1+np.exp(-z))


In [66]:
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights,bias

(array([[ 0.43801956],
        [-0.11781338]]), array([-0.42545066]))

In [67]:
#input layer has x1,x2,1
#output layer has output connectes via weights and bias term to the input layer
out_1=X
output=sig(np.dot(out_1,weights)+bias)
output

array([[0.39521319],
       [0.36742861],
       [0.50314218],
       [0.47371314]])

In [68]:
#backpropagation
#Here we'll use gradient descent
#first, we will try to minimize the error function with respect to the weights because we want to alter the weights
#so as to get the desired results
#dE/dwij has to be found
#Error=((ypred-yactual)**2)/2
#dE/dwij=(dE/doi)(doi/dinput)(dinput/dwij)
#(dE/dOj) for output layer is (ypred-yactual) ------term 1
#dinput/dwij=oi(prev layer ka input jisse wij is multiplied)----term 2 
#common for both wij
#doj/dinput=oj(1-oj) as oj=input(input)----term3


In [69]:
def diffsig(z):
    return sig(z)*(1-sig(z))

In [70]:
output-Y

array([[ 0.39521319],
       [-0.63257139],
       [-0.49685782],
       [-0.52628686]])

In [71]:
for iter in range(10000):
    out_1=X
    output=sig(np.dot(out_1,weights)+bias)
    lr=0.2 #learning rate
    first_term=output-Y
    prev_input=bias+np.dot(X,weights)
    second_term=diffsig(prev_input)
    first_two=first_term*second_term
    #third term gives ith term of prev layer i.e. ith input
    delta=np.array([[0.0],[0.0]]) #2x1 2 rows 1 column
    for i in range(2): #iterating through each column
        for j in range(4): #iterating through each row
            delta[i][0]+=first_two[j][0]*X[j][i]
    del_bias=0
    for j in range(4):
        del_bias+=first_two[j][0]*1
    bias=bias-lr*del_bias
    weights=weights-lr*delta
output

array([[0.03778658],
       [0.97630227],
       [0.9763027 ],
       [0.99997686]])